// The epistemic separation the whole project depends on: every object the
// renderer produces must carry a classification saying what kind of thing
// it is, so the world's beauty never gets mistaken for its evidence.
export type Classification =
  | "REAL_DATA" // verified public dataset (OpenStreetMap etc.)
  | "DERIVED_DATA" // computed directly from real data (e.g. extrusion height)
  | "COMPUTED_RELATION" // a deterministic relationship between two+ entities
  | "PROCEDURAL_OBJECT" // generated by seeded rules, not observed
  | "SYMBOLIC_OBJECT" // a stand-in / archetype, not a claim about reality
  | "ARTISTIC_INTERPRETATION"; // explicitly non-literal creative layer

export interface Provenance {
  classification: Classification;
  source?: {
    id: string;
    attribution: string;
    api?: string;
    fetchedAt?: string;
  };
  algorithm?: string;
  seed?: number | string;
  confidence?: "verified" | "estimated" | "illustrative";
  note?: string;
}

export const CLASSIFICATION_LABEL: Record<Classification, string> = {
  REAL_DATA: "Verified public data",
  DERIVED_DATA: "Derived from public data",
  COMPUTED_RELATION: "Computed relation",
  PROCEDURAL_OBJECT: "Procedurally generated",
  SYMBOLIC_OBJECT: "Symbolic construct",
  ARTISTIC_INTERPRETATION: "Artistic interpretation",
};

export const CLASSIFICATION_COLOR: Record<Classification, string> = {
  REAL_DATA: "#5ec98f",
  DERIVED_DATA: "#8fd0e8",
  COMPUTED_RELATION: "#c9a2f5",
  PROCEDURAL_OBJECT: "#e8c26a",
  SYMBOLIC_OBJECT: "#e88fae",
  ARTISTIC_INTERPRETATION: "#e88f6a",
};
